### PR TITLE
Front-end bug fixes, GraphView tweaks

### LINKED ISSUE #59: 'No data to retrieve' prevents `GraphView` from loading
If a user tries to load Node data before that Node has been executed, a "Loading data..." message appears behind the visual node. This does not disappear, nor can the user click the "view data" icon, even after execution.

Steps to reproduce:
1) Drag a `Read CSV` node to the workspace and select a file to read.
2) Click the 'table icon' and choose 'Load'.
3) The server responds with an error message that there's no data to retrieve.
4) The user executes the Node (to create the data to retrieve).
5) User cannot click the 'table icon' and the "Loading data..." message remains in the workspace.

Easiest change is probably to make the 'table icon' disabled until the Node reaches the 'complete' state (green). This would prevent loading data in the following use case:
1) User executes `Read CSV`.
2) User changes the file/config which changes the node to 'configured' and the 'table icon' disabled.
3) Data still exists from the execution in step 1, but it is not accessible.

but this should be fine, because the data from step 1 is now out-of-date and having the option to view it could lead to confusion.

giphy-2

[Screen recording](https://www.dropbox.com/s/2ay4sheq4i97btj/View%20data%20bug.mov?dl=0)

### LINKED ISSUE #60: `GraphView` button layout and window size
I would suggest a few more changes to make the `GraphView` a little more user-friendly.

1) Increase the size of the modal pop-up. It will never be large enough to handled the biggest data sets. Right now it has a `max-width` of 500px (at smaller breakpoints it increases to the window size).
2) Before data is loaded, the button options are currently 'Accept' and 'Load'. I would propose changing 'Accept' to 'Cancel'.
3) After data is loaded and viewing it graphically, the button text is 'Accept'. I would propose changing this to 'Done' or 'Okay'.
4) Cell highlighting alternates by row and column (e.g. A1 is shaded, B1 is not and the opposite for the second row). I would propose cell shading is constant by row (e.g. row 1 is shaded, row 2 is not), without alternating by column.

Screen Shot 2020-04-18 at 9 29 36 AM

### LINKED ISSUE #74: Front end edge creation  bug
I just remembered this and wanted to record it before I forgot. The JS API method that creates links uses the `getSourcePort` and `getTargetPort` methods on the react-diagrams link model to get the node IDs for the edge creation endpoint. But these correspond to the port where the user started dragging and the port where they stopped, respectively, **rather than the out- and in-ports**. Meaning if someone drew a link backwards, the DiGraph edge would be backwards. We need to add a step to the JS API method that determines which of the two ports is of type `out`, and sets that as the first parameter in the API call.

### PR DESCRIPTION
**Pull request by reelmatt**
**Fixes #59**: Updates the `Load` button in the `Modal.Footer` to be disabled if the Node has not been executed (i.e. `!= 'complete'`) and therefore no data available. The same status message appears whether there is data or not. For cases where there is a large file to load, a `react-spinners-css` Component now appears instead of the "Loading data..." message.

**Fixes #60**: Increased the `max-width` attribute for `.modal-dialog` which also affects the non-GraphView windows. This is great for the case where there is a large data file to display, but not great for smaller files/other Modal windows. I couldn't easily target a child of the `.modal-dialog` so I committed as-is.

Part of this fix also includes a clean-up of the `computeWidths` function to make the row/column names clearer. It also calculates the `maxWidth` of the Grid which allows to dynamically adjust the size for smaller data files. The default size has been bumped from 480x150 to 600x1000.

The grid style has also been tweaked slightly to shade every other row (and *not* alternate by columns) and adds a slight border on the edges.

**Fixes #74**: Adjusts the API call so that the NetworkX representation on the back will always store an edge from `outPort -> inPort` regardless of whether the user creates the edge in reverse.

### CODE REVIEW

**Comment by reddigari** [comment]
Great fixes!

I would recommend targeting the modal classes specifically using the `dialogClassName` attribute on the `Modal` component ([see here](https://react-bootstrap.github.io/components/modal/#modal-custom-sizing)). I think I used it to specifically style the node config form in #78, so it's probably better to not style all modals the same.

Tiny thing --- in my browser the data table extends over the modal width:
Screen Shot 2020-05-01 at 4 50 07 PM

File: front-end/src/components/CustomNode/GraphView.js [hunk 1]
```diff
@@ -32,109 +33,124 @@ export default class GraphView extends React.Component {
...
       }
 
-      if (this.state.columnCount < 1) {
-        return (
-          <Modal show={this.props.show} onHide={this.props.toggleShow} centered
-             onWheel={e => e.stopPropagation()}>
-          <Modal.Header>
-              <Modal.Title><b>{this.props.node.options.name}</b> View</Modal.Title>
+      return (
+          <Modal
```
Comment (reddigari) [inline front-end/src/components/CustomNode/GraphView.js:141]: Using the `dialogClassName` prop should allow you style this modal and its children specifically

Comment (reelmatt) [reply front-end/src/components/CustomNode/GraphView.js:143]: Exactly what I was looking for, thanks! Fixed in 5b593e4.

**Comment by reelmatt** [comment]
Thanks for the recommendation of `dialogClassName`.

Re: sizing, I tweaked the styles for the Grid so it shouldn't extend past the modal window anymore. It should also be centered, but that seems to be true only for larger data sets (small data is still left-aligned with a bunch of white-space).
